import argparse
import asyncio
import os
import sys
import time
from datetime import datetime
from urllib.parse import urlparse

from bbb_dl.utils import Log, PathTools as PT


def parse_netscape_cookies(content: str):
    """Parses Netscape cookie file content into a list of dicts."""
    cookies = []
    for line in content.splitlines():
        line = line.strip()
        if not line or line.startswith('#'):
            continue
        parts = line.split('\t')
        if len(parts) >= 7:
            cookies.append({
                'domain': parts[0],
                'flag': parts[1],
                'path': parts[2],
                'secure': parts[3].upper() == 'TRUE',
                'expires': int(parts[4]) if parts[4].isdigit() else 0,
                'name': parts[5],
                'value': parts[6],
            })
    return cookies


def format_netscape_cookies(cookies: list) -> str:
    """Formats list of cookie dicts back to Netscape cookie format."""
    lines = [
        "# Netscape HTTP Cookie File",
        "# https://curl.haxx.se/rfc/cookie_spec.html",
        "# This file was generated by bbb-dl",
        "",
    ]
    for c in cookies:
        flag = "TRUE" if c['domain'].startswith('.') else "FALSE"
        secure = "TRUE" if c.get('secure', True) else "FALSE"
        expires = str(c.get('expires', 0))
        path = c.get('path', '/') or '/'
        lines.append(f"{c['domain']}\t{flag}\t{path}\t{secure}\t{expires}\t{c['name']}\t{c['value']}")
    lines.append("")
    return "\n".join(lines)


def get_default_cookies_path(working_dir: str = None) -> str:
    """Returns the path to cookies.txt given a working directory."""
    if working_dir:
        base_dir = working_dir
    else:
        base_dir = PT.get_project_data_directory()
    os.makedirs(base_dir, exist_ok=True)
    return os.path.join(base_dir, "cookies.txt")


def save_cookie(
    domain: str,
    name: str,
    value: str,
    path: str = "/",
    secure: bool = True,
    expires: int = None,
    cookies_path: str = None,
):
    """Adds or updates a cookie in the cookies.txt file."""
    cookies_path = cookies_path or get_default_cookies_path()
    existing_cookies = []
    if os.path.isfile(cookies_path):
        with open(cookies_path, "r", encoding="utf-8") as f:
            existing_cookies = parse_netscape_cookies(f.read())

    # Default expiration: 1 year from now if not specified or session
    if not expires or expires <= 0:
        expires = int(time.time()) + 365 * 24 * 3600

    domain = domain.strip().lower()
    # Normalize domain: remove protocol or path if user passed full URL
    if "://" in domain:
        domain = urlparse(domain).hostname or domain
    elif "/" in domain:
        domain = domain.split("/")[0]

    # Remove existing cookie with same domain and name
    updated = [c for c in existing_cookies if not (c['domain'] == domain and c['name'] == name)]
    updated.append({
        'domain': domain,
        'flag': "TRUE" if domain.startswith('.') else "FALSE",
        'path': path or '/',
        'secure': secure,
        'expires': expires,
        'name': name.strip(),
        'value': value.strip(),
    })

    with open(cookies_path, "w", encoding="utf-8") as f:
        f.write(format_netscape_cookies(updated))

    Log.success(f"Saved cookie '{name}' for domain '{domain}' into {cookies_path}")


def list_cookies(cookies_path: str = None):
    """Lists all stored cookies."""
    cookies_path = cookies_path or get_default_cookies_path()
    if not os.path.isfile(cookies_path):
        Log.yellow(f"No cookies file found at {cookies_path}")
        return

    with open(cookies_path, "r", encoding="utf-8") as f:
        cookies = parse_netscape_cookies(f.read())

    if not cookies:
        Log.yellow(f"Cookies file at {cookies_path} is empty.")
        return

    Log.info(f"Stored cookies in {cookies_path}:")
    print("-" * 80)
    for c in cookies:
        exp_str = (
            datetime.fromtimestamp(c['expires']).strftime('%Y-%m-%d %H:%M:%S')
            if c['expires'] > 0
            else "Session"
        )
        print(f"Domain : {c['domain']}")
        print(f"Name   : {c['name']}")
        print(f"Path   : {c['path']} | Secure: {c['secure']} | Expires: {exp_str}")
        val_display = c['value'][:50] + "..." if len(c['value']) > 50 else c['value']
        print(f"Value  : {val_display}")
        print("-" * 80)


def clear_cookies(cookies_path: str = None):
    """Clears stored cookies."""
    cookies_path = cookies_path or get_default_cookies_path()
    if os.path.isfile(cookies_path):
        os.remove(cookies_path)
        Log.success(f"Removed cookies file: {cookies_path}")
    else:
        Log.yellow(f"No cookies file found at {cookies_path}")


async def run_interactive_login(target: str, cookies_path: str):
    """Launches Playwright browser to allow interactive user login and capture cookies."""
    from playwright.async_api import async_playwright

    target_url = target
    if not target_url.startswith("http://") and not target_url.startswith("https://"):
        target_url = "https://" + target_url

    parsed = urlparse(target_url)
    hostname = parsed.hostname or target_url

    Log.info(f"Launching browser to log into {target_url}...")
    try:
        async with async_playwright() as p:
            try:
                browser = await p.chromium.launch(headless=False)
            except Exception as e:
                Log.error(f"Failed to launch graphical browser: {e}")
                Log.yellow("You can set cookies manually using:")
                Log.yellow(f"    bbb-dl auth set-cookie {hostname} <cookie_name> <cookie_value>")
                return

            context = await browser.new_context()
            page = await context.new_page()

            try:
                await page.goto(target_url, timeout=60000)
            except Exception as nav_err:
                Log.warning(f"Initial navigation notice: {nav_err}")

            Log.yellow("=================================================================")
            Log.yellow(f" Browser opened for: {target_url}")
            Log.yellow(" Please log into your account in the browser window.")
            Log.yellow(" Once you are logged in, press [Enter] in this terminal to save cookies.")
            Log.yellow("=================================================================")

            # Wait for Enter in a non-blocking thread or browser close
            loop = asyncio.get_running_loop()
            await loop.run_in_executor(None, input)

            extracted_cookies = await context.cookies()
            await browser.close()

            if not extracted_cookies:
                Log.warning("No cookies were captured from the browser session.")
                return

            # Merge captured cookies into cookies.txt
            existing = []
            if os.path.isfile(cookies_path):
                with open(cookies_path, "r", encoding="utf-8") as f:
                    existing = parse_netscape_cookies(f.read())

            captured_keys = {(c['domain'], c['name']) for c in extracted_cookies}
            kept = [c for c in existing if (c['domain'], c['name']) not in captured_keys]

            for ec in extracted_cookies:
                exp = int(ec['expires']) if ec.get('expires') and ec['expires'] > 0 else int(time.time()) + 365 * 86400
                kept.append({
                    'domain': ec['domain'],
                    'flag': "TRUE" if ec['domain'].startswith('.') else "FALSE",
                    'path': ec.get('path', '/') or '/',
                    'secure': ec.get('secure', True),
                    'expires': exp,
                    'name': ec['name'],
                    'value': ec['value'],
                })

            with open(cookies_path, "w", encoding="utf-8") as f:
                f.write(format_netscape_cookies(kept))

            Log.success(f"Successfully saved {len(extracted_cookies)} cookies to {cookies_path}")

    except Exception as err:
        Log.error(f"Error during interactive login: {err}")


def auth_main(argv=None):
    """CLI entrypoint for `bbb-dl auth`."""
    if argv is None:
        argv = sys.argv[2:]

    parser = argparse.ArgumentParser(
        prog="bbb-dl auth",
        description="Manage authentication and session cookies for BigBlueButton recordings",
    )
    parser.add_argument(
        '-wd',
        '--working-dir',
        type=str,
        default=None,
        help='Optional directory where cookies.txt is stored (defaults to project data directory)',
    )

    subparsers = parser.add_subparsers(dest="subcommand", help="Authentication commands")

    # login command
    login_parser = subparsers.add_parser(
        "login",
        help="Open a browser to log into a BBB/LMS portal and save session cookies",
    )
    login_parser.add_argument(
        "target",
        type=str,
        help="Hostname or URL of the BigBlueButton or LMS server (e.g. bbb.example.com or https://moodle.example.com)",
    )

    # set-cookie command
    set_parser = subparsers.add_parser(
        "set-cookie",
        help="Manually save a cookie for a specific hostname",
    )
    set_parser.add_argument("domain", type=str, help="Hostname / domain (e.g. bbb.example.com)")
    set_parser.add_argument("name", type=str, help="Cookie name (or 'name=value' string)")
    set_parser.add_argument("value", type=str, nargs="?", default=None, help="Cookie value")
    set_parser.add_argument("--path", type=str, default="/", help="Cookie path (default: /)")
    set_parser.add_argument(
        "--expires",
        type=int,
        default=None,
        help="Expiration Unix timestamp (default: 1 year from now)",
    )

    # list command
    subparsers.add_parser("list", help="List all stored cookies")

    # clear command
    subparsers.add_parser("clear", help="Clear all stored cookies")

    args = parser.parse_args(argv)
    cookies_path = get_default_cookies_path(args.working_dir)

    if args.subcommand == "login":
        asyncio.run(run_interactive_login(args.target, cookies_path))
    elif args.subcommand == "set-cookie":
        cookie_name = args.name
        cookie_val = args.value
        # Support name=value format if value omitted
        if cookie_val is None and "=" in cookie_name:
            cookie_name, cookie_val = cookie_name.split("=", 1)
        elif cookie_val is None and " " in cookie_name:
            cookie_name, cookie_val = cookie_name.split(" ", 1)

        if not cookie_val:
            Log.error("Error: Cookie value must be provided.")
            sys.exit(1)

        save_cookie(
            domain=args.domain,
            name=cookie_name,
            value=cookie_val,
            path=args.path,
            expires=args.expires,
            cookies_path=cookies_path,
        )
    elif args.subcommand == "list":
        list_cookies(cookies_path)
    elif args.subcommand == "clear":
        clear_cookies(cookies_path)
    else:
        parser.print_help()
